### ISSUE TITLE
Unhandled exception in PartisanPrimary

### ISSUE THREAD

**Issue by JDziurlaj** [google/election_results_xml_validator#103]
If a `CandidateContest` in a primary does have `PrimaryPartyIds`, a error is to be reported. However, because `PrimaryPartyIds` can be `None`, the error cannot reliably report the `sourceline`. Instead an unhanded exception will be thrown at line 673.

https://github.com/google/election_results_xml_validator/blob/c02b6fe1536b660ee70fd51cbc14d5d75f16f538/rules.py#L666-L673

**Comment by jloutsenhizer** [comment]
This has been fixed by #140
