### ISSUE TITLE
Labels should be unique within a file 

### ISSUE THREAD

**Issue by ccongchen** [google/election_results_xml_validator#12]
An example of violation would be, BallotMeasureSelection elements all have the label of "bmslabel".

**Comment by miano** [comment]
@jdmgoogle How is the label attribute meant to be used? Is it wrong to have multiple elements with the same label e.g. the following.

<Candidate objectId="cand_52889100079">
        <BallotName label="ballotname">
                  <Text language="us-en">Keith Pittman</Text>
        </BallotName>
        <PartyId>par_7227b77354f8b135ac30be9ba289d159</PartyId>
</Candidate>
<Candidate objectId="cand_5288999900">
        <BallotName label="ballotname">
                  <Text language="us-en">Maria Mercedes Tio</Text>
        </BallotName>
        <PartyId>par_7227b77354f8b135ac30be9ba289d159</PartyId>
</Candidate>

The documentation just states that "For use as needed and compatibility with the VIP schema."

**Comment by jdmgoogle** [comment]
@miano Yes, the example you provided is an example of incorrect usage of the label. A label is similar to an ID, in that it uniquely identifies a piece of data in the file. The only differences are:

1. ID uniqueness is enforced by standard schema checkers; and
2. We use ID in places where other elements will reference them (via an IDREF) but labels in places where nothing else will reference them.

**Comment by miano** [comment]
Ok. Thanks!
