### ISSUE TITLE
Check if valid enumeration value is encoded as OtherType

### ISSUE THREAD

**Issue by jdmgoogle** [google/election_results_xml_validator#45]
We've seen several instances where a valid enumeration value is instead stored in the `OtherType` field. E.g.,

```xml
<GpUnit objectId="ru1" xsi:type="ReportingUnit">
  <Name>Virginia</Name>
  <Type>other</Type>
  <OtherType>state</Type>
</GpUnit>
```

Even though `state` is a valid `ReportingUnitType`, it has been represented in the `OtherType` field. The correct XML should be

```xml
<GpUnit objectId="ru1" xsi:type="ReportingUnit">
  <Name>Virginia</Name>
  <Type>state</Type>
</GpUnit>
```

This is an error since it can cause ingestion to fail.

**Comment by jloutsenhizer** [comment]
Fixed by #85
