### ISSUE TITLE
Better call out the specific missing elements instead of listing all

### ISSUE THREAD

**Issue by ccongchen** [google/election_results_xml_validator#82]
E.g. the following message is printed when only the Selection element is missing.
--------
  1528 Error messages found
      1528 Schema Error messages
        6254: Element 'BallotSelection': Missing child element(s). Expected is one of ( VoteCountsCollection, Selection ).

**Comment by jloutsenhizer** [comment]
Closing this out as obsolete. The output has become a lot more detailed since this issue was created. We can reopen or create a new issue if there's more detail needed.
